### ISSUE TITLE
How to draw intra- and interspecies synteny blocks the same time?

### ISSUE THREAD

**Issue by justdx** [TickingClock1992/RIdeogram#13]
Dear Hao, 
Thanks for the nice tool first. As mentioned in the title, I would like to ask how to draw both intra- and interspecies synteny blocks, such as Figure 1d in the Liriodendron genome paper? 
<img width="634" alt="fig1d" src="https://user-images.githubusercontent.com/39363003/84998738-ceb42a00-b182-11ea-8ebc-11ec0f39e8bb.png">

**Comment by TickingClock1992** [comment]
Hello, thanks for following our research paper. Originally, RIdeogram was developed to plot this figure. However, it is a little bit difficult to merge all the functions into the R package RIdeogram. If you want to draw the  intra- and interspecies synteny blocks the same time, I can sent the original script that I used to plot this figure. Leave me your e-mail address.

**Comment by justdx** [comment]
My email address is justdx0713@gmail.com, thanks a lot for your help.

**Comment by TickingClock1992** [comment]
No problem！

**Comment by evolgen** [comment]
Hi Hao,

Is there a plan to add functionality for intra- and inter- synteny in the upcoming versions of RIdeogram?
And is it possible to add gene coordinates adjacent to the chromosomes while plotting synteny?

**Comment by TickingClock1992** [comment]
Yes, of course. And, if you need to add intra- and inter- syntenic links now, you can send me your e-mail address. I will give you the raw script I used before for intra- and inter- synteny at chromosomal level and also gene synteny.

**Comment by evolgen** [comment]
Thanks a ton Hao - it is rohit@bioinf.uni-leipzig.de
I might have missed something in the marker info, since it has chromosome number and coordinates with colors, but the species represented is absent. Is it possible to add a species column to a track label?
