### ISSUE TITLE
how to make the input data for synteny_dual_comparison

### ISSUE THREAD

**Issue by niuhuifei** [TickingClock1992/RIdeogram#15]
Thanks for this good tool. I am new for this software and can you give some information of how to make the input file for synteny analysis, I mean transfer the resulted .collinearity file from MCScanX into RIdeogram because the file from MCScan have no chromosome info. Many thanks.

**Comment by TickingClock1992** [comment]
Then, you just need the genome annotation file to connect the gene id to its positional information in chromosomes.
