### ISSUE TITLE
HOW TO : Change front size, make horizontal layout of the ideogram

### ISSUE THREAD

**Issue by bbalog87** [TickingClock1992/RIdeogram#17]
Dear Hao,
Thank you for the useful package RIdeogram.
I couldn't find any parameter to create an horizontal ideogram instead of the default vertical.
Also I wanted to increase the font size of the labels. Are these options implemented yet in the package?

Best regards,
Julien

**Comment by TickingClock1992** [comment]
Hello, there is still no parameter for both ‘horizontal’ ideograms and the label size adjustment in this version. We are trying to add more options in the updates. Sorry for that.
