### ISSUE TITLE
how to move legend?

### ISSUE THREAD

**Issue by juancrescente** [TickingClock1992/RIdeogram#3]
![chromosome](https://user-images.githubusercontent.com/2141907/56825963-3564de80-6831-11e9-805a-ff35ddd498a2.png)

The top legend overlaps with the plot, can I move it elsewhere?

**Comment by juancrescente** [comment]
actually I'd like to customize the legend, leave only the features (shapes) and hide the Low - High overlay

**Comment by TickingClock1992** [comment]
If you want to move the Legend, then you need to modify the arguments ‘Lx’ and ‘Ly’(default values are “160” and “35”, separately).

‘Lx’ means the distance between upper-left point of the Legend and the left margin; ‘Ly’ means the distance between upper-left point of the Legend and the upper margin.
