### ISSUE TITLE
How to set the midpoint of colour

### ISSUE THREAD

**Issue by QianzhaoJ** [TickingClock1992/RIdeogram#4]
Hi:
    So useful package this is !
    However, I have some annotion data like ：

> 	1	3000500	3136999	-0.338434787450111	
	1	37321500	37489499	-0.533675006500781	
	1	37510500	37673999	-0.567659305780682	
	1	49247000	49471999	-0.781532436705488	
	1	153160500	153286999	-0.275541774503734	

The range of fourth column is `-0.9,0.5` ,and I want to set 0 as the midpoint of colours，**Ideogram** seems to set the mean as the midpoint of colours.  
Could you give me some advice ?
Thanks in advance !

**Comment by TickingClock1992** [comment]
Sorry for some delay with response. Now, **_Ideogram_** set the mean as the midpoint of color. We are planning to add the function that users can set the value for the midpoint color. However, there is still an alternative way you can do this. "0" is about the two-thirds. You can write the code like this:
`ideogram(karyotype = human_karyotype, overlaid = gene_density, colorset1 = c("#d7191c", "#fdae61", "#ffffbf", "#2c7bb6"))`
Then, you can get a picture set the two-thirds value as the midpoint color.
![chromosome](https://user-images.githubusercontent.com/25069813/62925011-abc22800-bdb1-11e9-8fab-b2f6c191d454.jpg)

**Comment by pengbo233** [comment]
你好！
      请问下，图例的low high是否可以设置为我自己想要设置的数字，从脚本提供信息来看，只有移动legend,而没有设置上下限具体数值的参数
祝好！

**Comment by pengbo233** [comment]
想到了，可以直接修改SVG，嗯，谢谢

**Comment by Frankshi5011** [comment]
Hello, This is a great tool. Can I draw the ideogram for mouse cells? It seems that there is no mouse karyotype data in the package? 

Thanks

Frank

**Comment by TickingClock1992** [comment]
> Hello, This is a great tool. Can I draw the ideogram for mouse cells? It seems that there is no mouse karyotype data in the package?
> 
> Thanks
> 
> Frank

Hi, you can make your own ideogram file very easily in .TXT format and then read it as a data frame with the function `read.table`. Happy Drawing!

**Comment by Frankshi5011** [comment]
Thanks so much!
Huidong
