### ISSUE TITLE
Error when trying to put in labels

### ISSUE THREAD

**Issue by MartinLaforest** [TickingClock1992/RIdeogram#9]
Hello, I am running into this error when trying to add labels:

Error in if (label_type == "marker") { : argument is of length zero

It might be a newbie question but I'm stuck, so sorry for asking. Here is the command I run and the 3 files that are fed to R-Studio (attached): 
[files.zip](https://github.com/TickingClock1992/RIdeogram/files/4349934/files.zip)

ideogram(karyotype = Book4[,1-3], label = single, overlaid = `4xdead`)

**Comment by TickingClock1992** [comment]
Sorry for the delay. I think you just miss a parameter, i.e., "label_type". Maybe you can write your code like this:

ideogram(karyotype = Book4, label = single, label_type = "marker", overlaid = Fourxdead)

Then, you will get a picture like this
![chromosome](https://user-images.githubusercontent.com/25069813/78733839-2bbc8400-7979-11ea-9446-eb5ee96807ec.png)

Hope you all good!

**Comment by MartinLaforest** [comment]
Excellent! Thank you so much!

**Comment by TickingClock1992** [comment]
No problem! 😄

**Comment by GaiaCortinovis6** [comment]
Hi everyone, I am trying to map some genome-wide data with track labels next to the chromosome idiograms with RIdeogram but I don't understand why it does not work.

**This is my code:**
#upload files
karyotype <-read.table("bean_karyotype.txt", sep = "\t", header = T, stringsAsFactors = F)
print(karyotype)

data_Fst <-read.table("data2.txt", sep = ";", header = T, stringsAsFactors = F)
print(karyotype)

#ideogram with track labels
ideogram(karyotype, label = data_Fst, label_type = "marker", output = "chromosome.svg")
convertSVG("chromosome.svg", device = "png")

**This is the error that I have:**
![Screenshot (35)](https://user-images.githubusercontent.com/96616790/147343256-7fe0bf04-93d6-4010-8e7f-e82ea43bbd42.jpg)

I do not have a lot of expertise in R, I really hope you can help me.
Thanks,

Gaia

**Comment by TickingClock1992** [comment]
Hello,

Could you send me the input files? Then, I can run the scripts and see what happens.

Thanks,

Dong

**Comment by GaiaCortinovis6** [comment]
Hi Dong,

Attached are my input files: "bean_katyotype" and "data2".


[
[bean_karyotype.txt](https://github.com/TickingClock1992/RIdeogram/files/7779356/bean_karyotype.txt)
[data2.txt](https://github.com/TickingClock1992/RIdeogram/files/7779357/data2.txt)
](url)

**Comment by TickingClock1992** [comment]
Hello,

Happy New year. Sorry for the delay. 

The problem you have met is not actually a problem. All you need it to change the ‘Color’ into ‘color’ in data2.txt file. Then, you will get the figure as attached with this e-mail.

King regards,

Dong
